### ISSUE TITLE
[Bug] Jackson sealed classes are no longer detected

### ISSUE THREAD

**Issue by clragon** [SMILEY4/ktor-openapi-tools#73] opened 2023-11-16 20:24 UTC
As of version 2.7.x, it seems that all my sealed classes annotated with Jackson are no longer detected.

Previously, the output for a given class was the following:

```json
      "RemoteGithubProjectRequest-1" : {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "owner" : {
            "type" : "string"
          },
          "repo" : {
            "type" : "string"
          },
          "type" : {
            "$ref" : "#/components/schemas/ProjectType"
          }
        }
      },
      "RemoteGithubProjectRequest-2" : {
        "$ref" : "#/components/schemas/RemoteGithubProjectRequest-1"
      },
```

(why every class is doubled I am unsure).

when upgrading to version 2.7.0 or later, I instead get:

```json
      "ProjectRequest" : {
        "type" : "object"
      },
```

(which is the root of the sealed class).

The code behind this specific class is as follows:

```kt
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = "type"
)
@JsonSubTypes(
    JsonSubTypes.Type(value = RemoteGithubProjectRequest::class, name = "remote_github")
)
sealed interface ProjectRequest {
    val name: String
    val type: ProjectType
}

@JsonDeserialize(using = CaseInsensitiveEnumDeserializer::class)
@JsonSerialize(using = CaseInsensitiveEnumSerializer::class)
enum class ProjectType {
    REMOTE_GITHUB,
    GITHUB
}

data class RemoteGithubProjectRequest(
    override val name: String,
    val owner: String,
    val repo: String,
) : ProjectRequest {
    override val type = ProjectType.REMOTE_GITHUB
}
```

downgrading to version 2.6.0 restores the previous behaviour.

**Comment by SMILEY4** [comment] 2023-11-18 11:22
Hi,
After just quickly looking into this, i think the issue is a result of a "JacksonModule"-addon being removed from the library that generates the json-schemas from classes to resolve https://github.com/SMILEY4/ktor-swagger-ui/issues/60.
The problem was that fields starting with "is" were not included in schemas. "JacksonModule" was removed since it also seemed to remove these fields. Unfortunately, it was also responsible for resolving the inheritance/interfaces.
I'll investigate further.

**Comment by SMILEY4** [comment] 2024-01-15 21:00
Hi, sorry for the very late response :/
I'm trying to find a proper future-proof solution but for now i only have a workaround - with the disadvantages described in my previous comment.

```kotlin
    EncodingData.DEFAULT_SCHEMA_GENERATOR = SchemaGenerator(
        EncodingData
            .schemaGeneratorConfigBuilder()
            .with(JacksonModule()) // add back JacksonModule
            .build()
    )

    install(SwaggerUI) { /*...*/ }
````

**Comment by clragon** [comment] 2024-02-02 18:44
Thank you for your response.
I've stopped using inheritance for my data classes (doesn't bode well) so I dont have this problem anymore. 
From my side, this issue is therefore done. Feel free to keep it open though.

**Comment by SMILEY4** [comment] 2024-05-28 21:37
closing this issue since it should be resolved with upcoming version 3

**Closed as completed by SMILEY4** 2024-05-28 21:37 UTC
